name: Push to DockerHub

on:
  push:
    tags: [ 'v*' ]

jobs:

  push:
    name: Docker Push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    env:
      REPOSITORY_URL: registry.hub.docker.com
      IMAGE_NAME: emrahkk/krapp
      PLATFORM: 3.10-slim

    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        id: docker-build
        run: >-
          docker build
          --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          --build-arg RELEASE=$(cat VERSION)
          --build-arg VERSION=${{ github.sha }}
          -t $IMAGE_NAME
          -t $REPOSITORY_URL/$IMAGE_NAME:$(cat VERSION)
          -t $REPOSITORY_URL/$IMAGE_NAME:$(git rev-parse --short HEAD)
          -t $REPOSITORY_URL/$IMAGE_NAME:$PLATFORM
          -t $REPOSITORY_URL/$IMAGE_NAME:latest .
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REPOSITORY_URL }}
          username: emrahkk
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Image
        id: docker-push
        run: docker push --all-tags $REPOSITORY_URL/$IMAGE_NAME